/* Q7: additive pediatric question module. Q1–Q6 are preserved. */
(() => {
  'use strict';
  if (typeof QUESTIONS === 'undefined' || typeof state === 'undefined' || typeof refresh !== 'function') return;
  if (QUESTIONS.some(q => q.id === 7)) return;
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="940" height="465" viewBox="0 0 940 465"><rect width="940" height="465" fill="#f1f7ff"/><rect x="22" y="22" width="896" height="421" rx="20" fill="white" stroke="#d1e0f4" stroke-width="2"/><text x="50" y="72" font-size="27" font-weight="bold" fill="#235ca0" font-family="Arial,sans-serif">Q7 · DDH: painless limp in a walking toddler</text><rect x="48" y="101" width="390" height="245" rx="16" fill="#eef5ff" stroke="#9bbce9"/><text x="68" y="142" font-size="23" fill="#284967" font-family="Arial,sans-serif">3-year-old girl</text><text x="68" y="188" font-size="21" fill="#284967" font-family="Arial,sans-serif">Painless Trendelenburg gait</text><text x="68" y="234" font-size="21" fill="#284967" font-family="Arial,sans-serif">Left leg appears shorter</text><text x="68" y="280" font-size="21" fill="#284967" font-family="Arial,sans-serif">Gradual onset; afebrile</text><path d="M448 222h45m-12-12 12 12-12 12" fill="none" stroke="#3979bf" stroke-width="4"/><rect x="510" y="101" width="376" height="245" rx="16" fill="#eaf8f0" stroke="#97ceb1"/><text x="531" y="145" font-size="24" font-weight="bold" fill="#146747" font-family="Arial,sans-serif">Think DDH</text><text x="531" y="195" font-size="21" fill="#285e4b" font-family="Arial,sans-serif">Unstable hip lever arm</text><text x="531" y="239" font-size="21" fill="#285e4b" font-family="Arial,sans-serif">→ abductor inefficiency</text><text x="531" y="283" font-size="21" fill="#285e4b" font-family="Arial,sans-serif">→ pelvic drop / limp</text><rect x="48" y="367" width="838" height="49" rx="10" fill="#fff5e5"/><text x="467" y="398" text-anchor="middle" font-size="20" fill="#8b5d19" font-family="Arial,sans-serif">Check hip abduction + Galeazzi sign → AP pelvis X-ray → paediatric orthopaedics</text></svg>`;
  QUESTIONS.push({
    id:7, category:'儿童骨科与步态', difficulty:'重点', title:'3岁女童无痛性跛行：Trendelenburg 步态', en_title:'Developmental dysplasia of the hip in a walking toddler',
    stem:'A mother brings her 3-year-old daughter to see you as her carers reported that she is walking differently from the other children at nursery.\n\nWhen walking around the examination room, you observe that she walks with a Trendelenberg gait. She does not appear to be in any discomfort. On examination, you believe her left leg might be slightly shorter than her right.\n\nShe is otherwise developing well, is of normal weight, and is afebrile. Her mother tells you she can’t remember when she first started mobilising like this, but she thinks it has crept up on them over months.\n\nWhat is the most likely diagnosis?',
    options:[['A','Developmental dysplasia of the hip'],['B','Perthes disease'],['C','Septic arthritis'],['D','Slipped upper femoral epiphysis'],['E','Transient synovitis']],
    answer:'A', answerName:'Developmental dysplasia of the hip (DDH，发育性髋关节发育不良)',
    key:'3岁女童＋数月逐渐出现的无痛性 Trendelenburg 步态＋疑似患侧短腿：晚发现的单侧 DDH / 髋关节半脱位或脱位是本题最佳匹配。',
    image:'data:image/svg+xml;charset=UTF-8,' + encodeURIComponent(svg),
    sections:[
      {heading:'一、诊断为什么指向 DDH？',body:'<p>这是<strong>已开始独立行走儿童的晚发现髋关节发育不良（developmental dysplasia of the hip, DDH）</strong>典型考法。题干给出女孩、无痛、缓慢出现步态异常、Trendelenburg gait，以及左下肢疑似短缩。髋臼发育不足或股骨头半脱位／脱位可使髋外展肌缺少稳定支点，导致骨盆控制不良；脱位侧还可出现表观下肢短缩。</p><p>“最可能”并非单凭 Trendelenburg 步态就确诊 DDH：髋外展肌无力及其他髋病同样可能出现该步态；这里是<strong>年龄＋无痛＋长短腿＋病程</strong>共同提高了 DDH 的符合度，实际仍需检查和影像证实。</p>'},
      {heading:'二、Trendelenburg 步态：从力学理解',body:'<div class="flow"><span>正常：单脚站立，站立侧臀中肌／臀小肌收缩</span><i>↓</i><span>稳定骨盆，防止对侧骨盆下沉</span><i>↓</i><span>左髋 DDH：左侧外展肌的有效力臂／支点异常</span><i>↓</i><span>左脚承重时右侧骨盆可能下沉；躯干可向左倾斜代偿</span></div><p><strong>准确记法：</strong>站在患侧腿上时，对侧骨盆下沉（阳性 Trendelenburg 征）；走路可能向患侧摆动躯干。它提示髋外展机制异常，不能独自区分 DDH 和 Perthes 病。</p>'},
      {heading:'三、逐项鉴别：年龄、疼痛和时间轴',body:'<table class="study-table"><thead><tr><th>选项</th><th>典型线索与本题区别</th></tr></thead><tbody><tr><td>A DDH ✓</td><td>婴幼儿或学步期晚发现；可无痛跛行、髋外展受限、Galeazzi 征阳性、表观短腿、Trendelenburg 步态。</td></tr><tr><td>B Perthes 病</td><td>股骨头缺血性坏死，多见约4–10岁，也可无痛跛行或出现 Trendelenburg 步态；常有内旋、外展受限，部分有髋／大腿／膝痛。3岁女孩并非绝对不可能，但本题短腿和早幼儿背景更符合 DDH。</td></tr><tr><td>C 化脓性关节炎</td><td>通常急性起病、明显疼痛、活动受限甚至拒绝负重，可发热；属于需紧急排查的疾病。数月无痛且一般状况良好不典型，但无发热不能单独排除感染。</td></tr><tr><td>D SUFE／SCFE</td><td>股骨头骨骺滑脱，典型为青春期（约10–16岁），常与肥胖相关，可表现为髋／膝痛和内旋受限；3岁、体重正常明显不典型。</td></tr><tr><td>E 一过性滑膜炎</td><td>常为急性或亚急性跛行，常伴髋部不适、可能在病毒感染后发病，通常数日到1–2周改善；持续数月及短腿不典型。</td></tr></tbody></table><p>考场警惕：Perthes 病也可以完全不痛，也能出现 Trendelenburg 步态；真正有鉴别价值的是综合年龄、腿长差、髋活动度及影像，而不是只用“是否疼痛”。</p>'},
      {heading:'四、如果接诊这位孩子，下一步检查什么？',body:'<p>观察步态及站立位骨盆；比较真实和表观下肢长度；检查髋关节外展、内旋及双侧活动度；做 <strong>Galeazzi（Allis）征</strong>——仰卧、双髋和双膝屈曲时患侧膝高度可较低。注意双侧 DDH 不一定出现腿长不等，较大婴儿／儿童的 Barlow、Ortolani 手法敏感性下降。</p><p>3岁儿童疑似 DDH 时通常选择<strong>骨盆正位 X 线片（AP pelvis radiograph）</strong>评估髋臼发育、股骨头位置等，并转诊儿童骨科。持续跛行不是只观察等待的情况。若突然不能负重、发热、剧痛或一般情况变差，应紧急排查感染等病因。</p>'},
      {heading:'五、资料来源',body:'<p><a href="https://www.nuh.com.sg/health-resources/diseases-and-conditions/developmental-hip-dysplasia" target="_blank" rel="noopener noreferrer">新加坡国立大学医院：DDH（幼儿可无痛跛行）</a>；<a href="https://pmc.ncbi.nlm.nih.gov/articles/PMC11965063/" target="_blank" rel="noopener noreferrer">The Pediatric Hip Physical Exam：Trendelenburg、Galeazzi 和髋活动度</a>；<a href="https://www.rch.org.au/ortho/for_health_professionals/Limping_child/" target="_blank" rel="noopener noreferrer">皇家儿童医院：跛行儿童的年龄分层与转诊</a>；<a href="https://www.rch.org.au/ortho/for_health_professionals/Perthes_Disease/" target="_blank" rel="noopener noreferrer">皇家儿童医院：Perthes 病鉴别</a>。</p>'}
    ],
    visualHtml:'<section class="note-section"><h3>🧠 记忆图卡：学步期无痛跛行</h3><div class="visual-note"><strong>DDH = 幼儿＋无痛性跛行＋患侧表观短腿＋Trendelenburg</strong><p>Perthes 可以无痛，但更常见于4–10岁；Trendelenburg 不是 DDH 特异性体征。图为原创示意图，不是题目截图或患者照片。</p></div></section>',
    takeaway:'学步期女孩，逐渐发生的无痛性 Trendelenburg 跛行＋疑似下肢不等长 → 优先考虑晚发现 DDH；骨盆 X 线评估并转儿童骨科。'
  });
  const intro = document.querySelector('.intro p');
  if (intro) intro.textContent = '按题号整理本对话中的 7 道儿科题目、英文原题、所有选项、答案与中文解析。Q1–Q5 原题截图保留；Q6–Q7 附自绘知识图卡，非原始题目截图。可搜索、收藏和打印。';
  const title = document.querySelector('.page-title');
  if (title) title.textContent = title.textContent.replace(/6\s*道/g,'7 道').replace(/6\s*题/g,'7 题');
  document.title = '儿科刷题档案 · 7道题';
  state.current = 7;
  refresh();
})();